name: "HEPHAI-PR-Doctor"
description: "An AI-powered GitHub Action for automated PR reviews & test suggestions."
author: "Your Name or FOX Techniques"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  github_token:
    description: "GitHub token to comment on PRs"
    required: true
  openai_api_key:
    description: "OpenAI API key for test suggestions"
    required: false

outputs:
  pr_score:
    description: "The calculated PR score from the analysis"

runs:
  using: "docker"
  image: "Dockerfile"
