name: Run Tests & Code Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install pytest pytest-cov mypy flake8 mutmut

    - name: Run Unit Tests with Coverage
      run: |
        pytest --cov=hephai_pr_doctor --cov-report=xml tests/
    
    - name: Run Static Analysis
      run: |
        mypy hephai_pr_doctor/
        flake8 hephai_pr_doctor/

    - name: Run Mutation Tests
      run: |
        mutmut run --paths-to-mutate=hephai_pr_doctor
        mutmut results

    - name: Upload Coverage to PR
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
